[package]
name = "rls-pretty-print"
version = "0.1.0"
authors = ["nemamdoost"]

[dependencies]
rls-analysis = {path = "/Users/nemamdoost/project/rls-analysis"}
rls-data = {version = "0.16.0", features = ["serialize-serde"] }
serde_json = "1.0.18"